import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import getHeadlines from "../actions/list";
import Header from "@/components/header";
import SideBar from "@/components/sidebar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headlines = await getHeadlines();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="page">
          <div className="w-full">
            <Header />
            <div className="flex w-full h-[80vh]">
              <SideBar data={headlines} />
              <div className="main  w-full bg-gray-600 text-white ">
                {children}
              </div>
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
